for i in range(5):
	n = int(input())
	
	if n == 1:
		print("          |")
		print("       \  |  /")
		print("        \ | /")
		print("         \|/")
		print("       XXXXXXX")
		print("      X       X")
		print("     X  O   O  X")
		print("    X     V     X")
		print("W   X  X     X  X")
		print(" \   X  XXXXX  X")
		print("  \   X       X")
		print("   \   XXXXXXX")
		print("    \ X       X---")
		print("     X    O    X  \\")
		print("    X           X  \\")
		print("     XXXXXXXXXXX    \\")
		print("      OOOO OOOO      M")
		print("      OOOO OOOO")
	
	if n == 2:
		print("          |")
		print("       \  |  /")
		print("        \ | /")
		print("         \|/")
		print("       XXXXXXX")
		print("      X       X")
		print("     X  O   O  X")
		print("    X     V     X")
		print("W   X  X     X  X")
		print(" \   X  XXXXX  X")
		print("  \   X       X")
		print("   \   XXXXXXX")
		print("    \ X       X---")
		print("     X    O    X  \\")
		print("    X           X  \\")
		print("     XXXXXXXXXXX    \\")
		print("     X         X     M")
		print("    X     O     X")
		print("   X      O      X")
		print("  X               X")
		print("   XXXXXXXXXXXXXXX")
		print("      OOOO OOOO")
		print("      OOOO OOOO")
	
	if n == 3:
		print("           |")
		print("        \  |  /")
		print("         \ | /")
		print("          \|/")
		print("        XXXXXXX")
		print("       X       X")
		print("      X  O   O  X")
		print("     X     V     X")
		print(" W   X  X     X  X")
		print("  \   X  XXXXX  X")
		print("   \   X       X")
		print("    \   XXXXXXX")
		print("     \ X       X---")
		print("      X    O    X  \\")
		print("     X           X  \\")
		print("      XXXXXXXXXXX    \\")
		print("      X         X     M")
		print("     X     O     X")
		print("    X      O      X")
		print("   X               X")
		print("    XXXXXXXXXXXXXXX")
		print("    X             X")
		print("   X       O       X")
		print("  X        O        X")
		print(" X         O         X")
		print("X                     X")
		print(" XXXXXXXXXXXXXXXXXXXXX")
		print("       OOOO OOOO")
		print("       OOOO OOOO")
	
	
	if n == 7:
		print("                                 |")
		print("                              \  |  /")
		print("                               \ | /")
		print("                                \|/")
		print("                              XXXXXXX")
		print("                             X       X")
		print("                            X  O   O  X")
		print("                           X     V     X")
		print("                       W   X  X     X  X")
		print("                        \   X  XXXXX  X")
		print("                         \   X       X")
		print("                          \   XXXXXXX")
		print("                           \ X       X---")
		print("                            X    O    X  \\")
		print("                           X           X  \\")
		print("                            XXXXXXXXXXX    \\")
		print("                            X         X     M")
		print("                           X     O     X")
		print("                          X      O      X")
		print("                         X               X")
		print("                          XXXXXXXXXXXXXXX")
		print("                          X             X")
		print("                         X       O       X")
		print("                        X        O        X")
		print("                       X         O         X")
		print("                      X                     X")
		print("                       XXXXXXXXXXXXXXXXXXXXX")
		print("                       X                   X")
		print("                      X          O          X")
		print("                     X           O           X")
		print("                    X            O            X")
		print("                   X             O             X")
		print("                  X                             X")
		print("                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                   X                           X")
		print("                  X              O              X")
		print("                 X               O               X")
		print("                X                O                X")
		print("               X                 O                 X")
		print("              X                  O                  X")
		print("             X                                       X")
		print("              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("              X                                     X")
		print("             X                   O                   X")
		print("            X                    O                    X")
		print("           X                     O                     X")
		print("          X                      O                      X")
		print("         X                       O                       X")
		print("        X                        O                        X")
		print("       X                                                   X")
		print("        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("        X                                                 X")
		print("       X                         O                         X")
		print("      X                          O                          X")
		print("     X                           O                           X")
		print("    X                            O                            X")
		print("   X                             O                             X")
		print("  X                              O                              X")
		print(" X                               O                               X")
		print("X                                                                 X")
		print(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                             OOOO OOOO")
		print("                             OOOO OOOO")
	
	
	if n == 8:
		print("                                         |")
		print("                                      \  |  /")
		print("                                       \ | /")
		print("                                        \|/")
		print("                                      XXXXXXX")
		print("                                     X       X")
		print("                                    X  O   O  X")
		print("                                   X     V     X")
		print("                               W   X  X     X  X")
		print("                                \   X  XXXXX  X")
		print("                                 \   X       X")
		print("                                  \   XXXXXXX")
		print("                                   \ X       X---")
		print("                                    X    O    X  \\")
		print("                                   X           X  \\")
		print("                                    XXXXXXXXXXX    \\")
		print("                                    X         X     M")
		print("                                   X     O     X")
		print("                                  X      O      X")
		print("                                 X               X")
		print("                                  XXXXXXXXXXXXXXX")
		print("                                  X             X")
		print("                                 X       O       X")
		print("                                X        O        X")
		print("                               X         O         X")
		print("                              X                     X")
		print("                               XXXXXXXXXXXXXXXXXXXXX")
		print("                               X                   X")
		print("                              X          O          X")
		print("                             X           O           X")
		print("                            X            O            X")
		print("                           X             O             X")
		print("                          X                             X")
		print("                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                           X                           X")
		print("                          X              O              X")
		print("                         X               O               X")
		print("                        X                O                X")
		print("                       X                 O                 X")
		print("                      X                  O                  X")
		print("                     X                                       X")
		print("                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                      X                                     X")
		print("                     X                   O                   X")
		print("                    X                    O                    X")
		print("                   X                     O                     X")
		print("                  X                      O                      X")
		print("                 X                       O                       X")
		print("                X                        O                        X")
		print("               X                                                   X")
		print("                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                X                                                 X")
		print("               X                         O                         X")
		print("              X                          O                          X")
		print("             X                           O                           X")
		print("            X                            O                            X")
		print("           X                             O                             X")
		print("          X                              O                              X")
		print("         X                               O                               X")
		print("        X                                                                 X")
		print("         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("         X                                                               X")
		print("        X                                O                                X")
		print("       X                                 O                                 X")
		print("      X                                  O                                  X")
		print("     X                                   O                                   X")
		print("    X                                    O                                    X")
		print("   X                                     O                                     X")
		print("  X                                      O                                      X")
		print(" X                                       O                                       X")
		print("X                                                                                 X")
		print(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                                     OOOO OOOO")
		print("                                     OOOO OOOO")
	
	
	if n == 9:
		print("                                                  |")
		print("                                               \  |  /")
		print("                                                \ | /")
		print("                                                 \|/")
		print("                                               XXXXXXX")
		print("                                              X       X")
		print("                                             X  O   O  X")
		print("                                            X     V     X")
		print("                                        W   X  X     X  X")
		print("                                         \   X  XXXXX  X")
		print("                                          \   X       X")
		print("                                           \   XXXXXXX")
		print("                                            \ X       X---")
		print("                                             X    O    X  \\")
		print("                                            X           X  \\")
		print("                                             XXXXXXXXXXX    \\")
		print("                                             X         X     M")
		print("                                            X     O     X")
		print("                                           X      O      X")
		print("                                          X               X")
		print("                                           XXXXXXXXXXXXXXX")
		print("                                           X             X")
		print("                                          X       O       X")
		print("                                         X        O        X")
		print("                                        X         O         X")
		print("                                       X                     X")
		print("                                        XXXXXXXXXXXXXXXXXXXXX")
		print("                                        X                   X")
		print("                                       X          O          X")
		print("                                      X           O           X")
		print("                                     X            O            X")
		print("                                    X             O             X")
		print("                                   X                             X")
		print("                                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                                    X                           X")
		print("                                   X              O              X")
		print("                                  X               O               X")
		print("                                 X                O                X")
		print("                                X                 O                 X")
		print("                               X                  O                  X")
		print("                              X                                       X")
		print("                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                               X                                     X")
		print("                              X                   O                   X")
		print("                             X                    O                    X")
		print("                            X                     O                     X")
		print("                           X                      O                      X")
		print("                          X                       O                       X")
		print("                         X                        O                        X")
		print("                        X                                                   X")
		print("                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                         X                                                 X")
		print("                        X                         O                         X")
		print("                       X                          O                          X")
		print("                      X                           O                           X")
		print("                     X                            O                            X")
		print("                    X                             O                             X")
		print("                   X                              O                              X")
		print("                  X                               O                               X")
		print("                 X                                                                 X")
		print("                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                  X                                                               X")
		print("                 X                                O                                X")
		print("                X                                 O                                 X")
		print("               X                                  O                                  X")
		print("              X                                   O                                   X")
		print("             X                                    O                                    X")
		print("            X                                     O                                     X")
		print("           X                                      O                                      X")
		print("          X                                       O                                       X")
		print("         X                                                                                 X")
		print("          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("          X                                                                               X")
		print("         X                                        O                                        X")
		print("        X                                         O                                         X")
		print("       X                                          O                                          X")
		print("      X                                           O                                           X")
		print("     X                                            O                                            X")
		print("    X                                             O                                             X")
		print("   X                                              O                                              X")
		print("  X                                               O                                               X")
		print(" X                                                O                                                X")
		print("X                                                                                                   X")
		print(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                                              OOOO OOOO")
		print("                                              OOOO OOOO")
	
	
	if n == 10:
		print("                                                            |")
		print("                                                         \  |  /")
		print("                                                          \ | /")
		print("                                                           \|/")
		print("                                                         XXXXXXX")
		print("                                                        X       X")
		print("                                                       X  O   O  X")
		print("                                                      X     V     X")
		print("                                                  W   X  X     X  X")
		print("                                                   \   X  XXXXX  X")
		print("                                                    \   X       X")
		print("                                                     \   XXXXXXX")
		print("                                                      \ X       X---")
		print("                                                       X    O    X  \\")
		print("                                                      X           X  \\")
		print("                                                       XXXXXXXXXXX    \\")
		print("                                                       X         X     M")
		print("                                                      X     O     X")
		print("                                                     X      O      X")
		print("                                                    X               X")
		print("                                                     XXXXXXXXXXXXXXX")
		print("                                                     X             X")
		print("                                                    X       O       X")
		print("                                                   X        O        X")
		print("                                                  X         O         X")
		print("                                                 X                     X")
		print("                                                  XXXXXXXXXXXXXXXXXXXXX")
		print("                                                  X                   X")
		print("                                                 X          O          X")
		print("                                                X           O           X")
		print("                                               X            O            X")
		print("                                              X             O             X")
		print("                                             X                             X")
		print("                                              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                                              X                           X")
		print("                                             X              O              X")
		print("                                            X               O               X")
		print("                                           X                O                X")
		print("                                          X                 O                 X")
		print("                                         X                  O                  X")
		print("                                        X                                       X")
		print("                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                                         X                                     X")
		print("                                        X                   O                   X")
		print("                                       X                    O                    X")
		print("                                      X                     O                     X")
		print("                                     X                      O                      X")
		print("                                    X                       O                       X")
		print("                                   X                        O                        X")
		print("                                  X                                                   X")
		print("                                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                                   X                                                 X")
		print("                                  X                         O                         X")
		print("                                 X                          O                          X")
		print("                                X                           O                           X")
		print("                               X                            O                            X")
		print("                              X                             O                             X")
		print("                             X                              O                              X")
		print("                            X                               O                               X")
		print("                           X                                                                 X")
		print("                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                            X                                                               X")
		print("                           X                                O                                X")
		print("                          X                                 O                                 X")
		print("                         X                                  O                                  X")
		print("                        X                                   O                                   X")
		print("                       X                                    O                                    X")
		print("                      X                                     O                                     X")
		print("                     X                                      O                                      X")
		print("                    X                                       O                                       X")
		print("                   X                                                                                 X")
		print("                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                    X                                                                               X")
		print("                   X                                        O                                        X")
		print("                  X                                         O                                         X")
		print("                 X                                          O                                          X")
		print("                X                                           O                                           X")
		print("               X                                            O                                            X")
		print("              X                                             O                                             X")
		print("             X                                              O                                              X")
		print("            X                                               O                                               X")
		print("           X                                                O                                                X")
		print("          X                                                                                                   X")
		print("           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("           X                                                                                                 X")
		print("          X                                                 O                                                 X")
		print("         X                                                  O                                                  X")
		print("        X                                                   O                                                   X")
		print("       X                                                    O                                                    X")
		print("      X                                                     O                                                     X")
		print("     X                                                      O                                                      X")
		print("    X                                                       O                                                       X")
		print("   X                                                        O                                                        X")
		print("  X                                                         O                                                         X")
		print(" X                                                          O                                                          X")
		print("X                                                                                                                       X")
		print(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
		print("                                                        OOOO OOOO")
		print("                                                        OOOO OOOO")
	
	if i != 4:
		print()
